"""empty message

Revision ID: f9f75906daac
Revises: 
Create Date: 2023-09-13 15:09:04.960797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9f75906daac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('whos_turn', sa.String(length=1), nullable=False),
    sa.Column('board', sa.String(), nullable=False),
    sa.Column('winner', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('game_id')
    )
    # ### end Alembic commands ###
  

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    # ### end Alembic commands ###
